name: 'Sync internal dependencies'
description: 'Linking internal dependencies inside monorepo npm project'
inputs:
  packages-path:
    description: 'Glob path to packages.json'
    required: false
    default: 'packages/**/package.json'
  sync-commit-message:
    description: 'Commit message after versions sync'
    required: false
    default: 'chore: synced versions for linked packages'
runs:
  using: 'node16'
  main: 'dist/index.js'